### PR TITLE
Adding contribution guidelines

### PR DESCRIPTION
**Pull request by Vaishu03**
Adding contribution guidelines for this repo as it can help the contributors.

### CODE REVIEW

**Review by Archiehere — COMMENTED** [review]
Nice Work! Can you add The discord link incase someone encounters an error. They may ask questions between one another.

**Comment by Vaishu03** [comment]
Do we have separate discord channel or shall I redirect hacktoberfest discord only?

**Comment by Archiehere** [comment]
> Do we have separate discord channel or shall I redirect hacktoberfest discord only?

We have a Discord. Here's the Link :- [Discord](https://discord.gg/DBba9McZDq)

**Comment by Vaishu03** [comment]
Okay thank you

**Pull request merged**
